version: "3.8"

services:
  victim:
    build:
      context: ..
      dockerfile: malcolm_lab/victim/Dockerfile
    container_name: victim
    privileged: true
    networks:
      - malcolm_net
    command: sleep infinity

  attacker:
    build:
      context: ..
      dockerfile: malcolm_lab/attacker/Dockerfile
    container_name: attacker
    privileged: true
    networks:
      - malcolm_net
    command: sleep infinity
  
  gateaway:
    build:
      context: ..
      dockerfile: malcolm_lab/gateaway/Dockerfile
    container_name: gateaway
    privileged: true
    networks:
      - malcolm_net
    command: sleep infinity
  
networks:
  malcolm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.100.0/24
